name: Product Service CI

on:
  push:
    paths:
      - "services/inventory_service/**"
  pull_request:
    paths:
      - "services/inventory_service/**"

jobs:
  ci:
    uses: ./.github/workflows/rails-ci.yml
    with:
      service-path: services/inventory_service